questions_list = [ 
    ("Is the sun a star?", "YES"),
    ("Can penguins fly?", "NO"),
    ("Is the moon bigger than Mars?", "NO"),
    ("Is water made of hydrogen?", "YES"),
    ("Is 5 × 6 equal to 30?", "YES"),
    ("Do sharks have bones?", "NO"),
    ("Is gold heavier than silver?", "YES"),
    ("Can bats see in the dark?", "YES"),
    ("Is an octopus a reptile?", "NO"),
    ("Do plants make oxygen?", "YES"),
    ("Can sound travel in space?", "NO"),
    ("Is a dolphin a mammal?", "YES"),
    ("Does Earth have two moons?", "NO"),
    ("Is 100 a prime number?", "NO"),
    ("Can cats taste sweetness?", "NO"),
    ("Do all birds lay eggs?", "YES"),
    ("Is iron heavier than lead?", "NO"),
    ("Was Einstein a scientist?", "YES"),
    ("Is Everest the tallest?", "YES"),
    ("Can humans breathe nitrogen?", "NO"),
    ("Is Pluto a planet?", "NO"),
    ("Is 12 × 12 equal to 144?", "YES"),
    ("Do ants have lungs?", "NO"),
    ("Can fish live without water?", "NO"),
    ("Is the Amazon a desert?", "NO"),
    ("Does fire need oxygen?", "YES"),
    ("Is chess a sport?", "YES"),
    ("Was Napoleon French?", "YES"),
    ("Can jellyfish sting humans?", "YES"),
    ("Is the Pacific the biggest?", "YES"),
    ("Can glass break under heat?", "YES"),
    ("Do turtles have teeth?", "NO"),
    ("Is Mercury the hottest?", "NO"),
    ("Can camels store water?", "NO"),
    ("Do elephants have tusks?", "YES"),  
    ("Can humans live on Mars?", "NO"),
    ("Is oxygen a metal?", "NO"),
    ("Was the Titanic a plane?", "NO"),
    ("Do bees make honey?", "YES"),
    ("Is coal a fossil fuel?", "YES"),
    ("Can some frogs fly?", "YES"),
    ("Do all snakes have venom?", "NO"),
    ("Is steel heavier than wood?", "YES"),
    ("Was Rome built in a day?", "NO"),
    ("Is Tokyo the capital of Japan?", "YES"),
    ("Do giraffes have short necks?", "NO"),
    ("Can ice sink in water?", "NO"),
    ("Is the moon made of cheese?", "NO"),
    ("Was the iPhone made in 1990?", "NO"),
    ("Is the square root of 49, 7?", "YES"),
]